const DATA = {
  stimuli: [
    {
      id: "AB37",
      citrus: 100,
      gourmand: 0,
      marine: 0,
      woody: 0,
      liking: 78.5,
      feels: {
        Irritating: 15.1,
        Luxurious: 28.3,
        Natural: 64.9,
        Nostalgic: 25.9,
        Offensive: 9.3,
        "Old-Fashioned": 25.4,
        Playful: 53.2,
        Refreshing: 75.1,
        Relaxing: 45.4,
        Romantic: 21.0,
        Soothing: 50.2,
        Sporty: 46.8,
        Surprising: 47.3,
        Trendy: 40.5,
        Vibrant: 70.2,
        Fresh: 80.5,
        Clean: 77.6,
        Artificial: 29.3,
        Cheery: 59.0,
        Comforting: 49.8,
        "like it gives you Confidence": 49.8,
        Dull: 9.8,
        Energising: 69.8,
        Familiar: 52.7,
        Harsh: 20.5,
        Intriguing: 52.2,
      },
      images: {
        "Emotions-I-feel-calm-and-at-peace": 51,
        "Emotions-I-feel-protected-and-reassured": 21,
        "Emotions-This-gives-me-a-burst-of-energy": 60,
        "Emotions-This-gives-me-confidence": 48,
        "Fragrance-Space-I-love-the-light,-airy-scent": 51,
        "Fragrance-Space-I-love-the-warm-essence": 24,
        "Fragrance-Space-It-feels-so-fresh": 57,
        "Fragrance-Space-It-has-a-luxurious-aura-about-it": 6,
        "Occasion-It-puts-me-in-a-meditative-state": 45,
        "Occasion-It's-fun-for-an-intimate-group-outing": 42,
        "Occasion-It's-perfect-for-big-gatherings": 39,
        "Occasion-It's-wonderful-for-spending-time-with-friends": 42,
        "Product-Format-It-does-a-great-job-of-eliminating-odours": 48,
        "Product-Format-It-has-a-brightening-effect": 33,
        "Product-Format-It-lathers-up-very-nicely": 45,
        "Product-Format-This-leaves-me-feeling-soft-and-smooth": 48,
        "Routine-It-helps-me-feel-ready-for-a-great-night-out": 18,
        "Routine-It-helps-me-start-my-day-off-right": 48,
        "Routine-It-helps-me-take-a-moment-just-for-myself": 45,
        "Routine-It-helps-me-wind-down-at-the-end-of-the-day": 33,
        "Sensorial-I-like-the-clean-allusion": 30,
        "Sensorial-I-love-how-smooth-and-creamy-it-is": 45,
        "Sensorial-I-love-the-bright,-sparkling-effect": 42,
        "Sensorial-I-love-the-rich,-deep-feeling": 15,
      },
    },
    {
      id: "BQ81",
      citrus: 25,
      gourmand: 25,
      marine: 25,
      woody: 25,
      liking: 55.6,
      feels: {
        Irritating: 30.2,
        Luxurious: 31.7,
        Natural: 47.3,
        Nostalgic: 27.8,
        Offensive: 18.0,
        "Old-Fashioned": 38.5,
        Playful: 31.7,
        Refreshing: 53.7,
        Relaxing: 40.5,
        Romantic: 18.5,
        Soothing: 39.0,
        Sporty: 30.7,
        Surprising: 39.5,
        Trendy: 26.3,
        Vibrant: 44.9,
        Fresh: 58.0,
        Clean: 66.3,
        Artificial: 50.7,
        Cheery: 33.7,
        Comforting: 38.5,
        "like it gives you Confidence": 34.1,
        Dull: 18.5,
        Energising: 47.3,
        Familiar: 38.0,
        Harsh: 36.6,
        Intriguing: 45.4,
      },
      images: {
        "Emotions-I-feel-calm-and-at-peace": 45,
        "Emotions-I-feel-protected-and-reassured": 9,
        "Emotions-This-gives-me-a-burst-of-energy": 54,
        "Emotions-This-gives-me-confidence": 51,
        "Fragrance-Space-I-love-the-light,-airy-scent": 36,
        "Fragrance-Space-I-love-the-warm-essence": 48,
        "Fragrance-Space-It-feels-so-fresh": 45,
        "Fragrance-Space-It-has-a-luxurious-aura-about-it": 21,
        "Occasion-It-puts-me-in-a-meditative-state": 48,
        "Occasion-It's-fun-for-an-intimate-group-outing": 39,
        "Occasion-It's-perfect-for-big-gatherings": 27,
        "Occasion-It's-wonderful-for-spending-time-with-friends": 39,
        "Product-Format-It-does-a-great-job-of-eliminating-odours": 45,
        "Product-Format-It-has-a-brightening-effect": 39,
        "Product-Format-It-lathers-up-very-nicely": 57,
        "Product-Format-This-leaves-me-feeling-soft-and-smooth": 42,
        "Routine-It-helps-me-feel-ready-for-a-great-night-out": 24,
        "Routine-It-helps-me-start-my-day-off-right": 36,
        "Routine-It-helps-me-take-a-moment-just-for-myself": 39,
        "Routine-It-helps-me-wind-down-at-the-end-of-the-day": 33,
        "Sensorial-I-like-the-clean-allusion": 27,
        "Sensorial-I-love-how-smooth-and-creamy-it-is": 24,
        "Sensorial-I-love-the-bright,-sparkling-effect": 42,
        "Sensorial-I-love-the-rich,-deep-feeling": 21,
      },
    },
    {
      id: "CS84",
      citrus: 50,
      gourmand: 0,
      marine: 50,
      woody: 0,
      liking: 73.4,
      feels: {
        Irritating: 16.9,
        Luxurious: 30.9,
        Natural: 61.4,
        Nostalgic: 27.5,
        Offensive: 12.6,
        "Old-Fashioned": 27.5,
        Playful: 43.0,
        Refreshing: 71.5,
        Relaxing: 46.4,
        Romantic: 19.8,
        Soothing: 46.9,
        Sporty: 42.0,
        Surprising: 44.4,
        Trendy: 35.3,
        Vibrant: 57.0,
        Fresh: 74.9,
        Clean: 77.3,
        Artificial: 34.3,
        Cheery: 45.4,
        Comforting: 44.9,
        "like it gives you Confidence": 44.4,
        Dull: 12.6,
        Energising: 60.4,
        Familiar: 46.4,
        Harsh: 23.7,
        Intriguing: 45.9,
      },
      images: {
        "Emotions-I-feel-calm-and-at-peace": 39,
        "Emotions-I-feel-protected-and-reassured": 24,
        "Emotions-This-gives-me-a-burst-of-energy": 57,
        "Emotions-This-gives-me-confidence": 45,
        "Fragrance-Space-I-love-the-light,-airy-scent": 45,
        "Fragrance-Space-I-love-the-warm-essence": 57,
        "Fragrance-Space-It-feels-so-fresh": 45,
        "Fragrance-Space-It-has-a-luxurious-aura-about-it": 18,
        "Occasion-It-puts-me-in-a-meditative-state": 57,
        "Occasion-It's-fun-for-an-intimate-group-outing": 36,
        "Occasion-It's-perfect-for-big-gatherings": 21,
        "Occasion-It's-wonderful-for-spending-time-with-friends": 30,
        "Product-Format-It-does-a-great-job-of-eliminating-odours": 48,
        "Product-Format-It-has-a-brightening-effect": 42,
        "Product-Format-It-lathers-up-very-nicely": 54,
        "Product-Format-This-leaves-me-feeling-soft-and-smooth": 54,
        "Routine-It-helps-me-feel-ready-for-a-great-night-out": 6,
        "Routine-It-helps-me-start-my-day-off-right": 42,
        "Routine-It-helps-me-take-a-moment-just-for-myself": 51,
        "Routine-It-helps-me-wind-down-at-the-end-of-the-day": 18,
        "Sensorial-I-like-the-clean-allusion": 33,
        "Sensorial-I-love-how-smooth-and-creamy-it-is": 45,
        "Sensorial-I-love-the-bright,-sparkling-effect": 36,
        "Sensorial-I-love-the-rich,-deep-feeling": 27,
      },
    },
    {
      id: "DY15",
      citrus: 33.34,
      gourmand: 33.33,
      marine: 33.34,
      woody: 0,
      liking: 74.3,
      feels: {
        Irritating: 18.4,
        Luxurious: 35.4,
        Natural: 56.8,
        Nostalgic: 27.7,
        Offensive: 10.2,
        "Old-Fashioned": 34.0,
        Playful: 40.8,
        Refreshing: 67.0,
        Relaxing: 45.6,
        Romantic: 23.8,
        Soothing: 48.5,
        Sporty: 41.3,
        Surprising: 44.7,
        Trendy: 36.9,
        Vibrant: 55.3,
        Fresh: 71.4,
        Clean: 73.3,
        Artificial: 37.4,
        Cheery: 44.7,
        Comforting: 46.1,
        "like it gives you Confidence": 42.2,
        Dull: 10.2,
        Energising: 58.7,
        Familiar: 48.1,
        Harsh: 24.3,
        Intriguing: 49.0,
      },
      images: {
        "Emotions-I-feel-calm-and-at-peace": 60,
        "Emotions-I-feel-protected-and-reassured": 21,
        "Emotions-This-gives-me-a-burst-of-energy": 36,
        "Emotions-This-gives-me-confidence": 39,
        "Fragrance-Space-I-love-the-light,-airy-scent": 39,
        "Fragrance-Space-I-love-the-warm-essence": 42,
        "Fragrance-Space-It-feels-so-fresh": 42,
        "Fragrance-Space-It-has-a-luxurious-aura-about-it": 24,
        "Occasion-It-puts-me-in-a-meditative-state": 45,
        "Occasion-It's-fun-for-an-intimate-group-outing": 45,
        "Occasion-It's-perfect-for-big-gatherings": 45,
        "Occasion-It's-wonderful-for-spending-time-with-friends": 36,
        "Product-Format-It-does-a-great-job-of-eliminating-odours": 51,
        "Product-Format-It-has-a-brightening-effect": 33,
        "Product-Format-It-lathers-up-very-nicely": 57,
        "Product-Format-This-leaves-me-feeling-soft-and-smooth": 60,
        "Routine-It-helps-me-feel-ready-for-a-great-night-out": 27,
        "Routine-It-helps-me-start-my-day-off-right": 39,
        "Routine-It-helps-me-take-a-moment-just-for-myself": 60,
        "Routine-It-helps-me-wind-down-at-the-end-of-the-day": 33,
        "Sensorial-I-like-the-clean-allusion": 27,
        "Sensorial-I-love-how-smooth-and-creamy-it-is": 45,
        "Sensorial-I-love-the-bright,-sparkling-effect": 51,
        "Sensorial-I-love-the-rich,-deep-feeling": 30,
      },
    },
    {
      id: "FA69",
      citrus: 33.33,
      gourmand: 33.34,
      marine: 0,
      woody: 33.33,
      liking: 58.2,
      feels: {
        Irritating: 23.1,
        Luxurious: 32.2,
        Natural: 49.5,
        Nostalgic: 27.9,
        Offensive: 15.4,
        "Old-Fashioned": 41.8,
        Playful: 31.2,
        Refreshing: 53.4,
        Relaxing: 45.2,
        Romantic: 19.2,
        Soothing: 47.1,
        Sporty: 36.1,
        Surprising: 36.5,
        Trendy: 28.8,
        Vibrant: 42.8,
        Fresh: 61.1,
        Clean: 63.5,
        Artificial: 41.3,
        Cheery: 37.5,
        Comforting: 41.3,
        "like it gives you Confidence": 33.7,
        Dull: 23.1,
        Energising: 43.8,
        Familiar: 43.3,
        Harsh: 28.4,
        Intriguing: 40.4,
      },
      images: {
        "Emotions-I-feel-calm-and-at-peace": 51,
        "Emotions-I-feel-protected-and-reassured": 18,
        "Emotions-This-gives-me-a-burst-of-energy": 36,
        "Emotions-This-gives-me-confidence": 48,
        "Fragrance-Space-I-love-the-light,-airy-scent": 42,
        "Fragrance-Space-I-love-the-warm-essence": 45,
        "Fragrance-Space-It-feels-so-fresh": 42,
        "Fragrance-Space-It-has-a-luxurious-aura-about-it": 18,
        "Occasion-It-puts-me-in-a-meditative-state": 57,
        "Occasion-It's-fun-for-an-intimate-group-outing": 36,
        "Occasion-It's-perfect-for-big-gatherings": 24,
        "Occasion-It's-wonderful-for-spending-time-with-friends": 36,
        "Product-Format-It-does-a-great-job-of-eliminating-odours": 48,
        "Product-Format-It-has-a-brightening-effect": 33,
        "Product-Format-It-lathers-up-very-nicely": 42,
        "Product-Format-This-leaves-me-feeling-soft-and-smooth": 42,
        "Routine-It-helps-me-feel-ready-for-a-great-night-out": 15,
        "Routine-It-helps-me-start-my-day-off-right": 39,
        "Routine-It-helps-me-take-a-moment-just-for-myself": 48,
        "Routine-It-helps-me-wind-down-at-the-end-of-the-day": 33,
        "Sensorial-I-like-the-clean-allusion": 39,
        "Sensorial-I-love-how-smooth-and-creamy-it-is": 45,
        "Sensorial-I-love-the-bright,-sparkling-effect": 42,
        "Sensorial-I-love-the-rich,-deep-feeling": 45,
      },
    },
    {
      id: "GR07",
      citrus: 0,
      gourmand: 33.33,
      marine: 33.33,
      woody: 33.34,
      liking: 45.9,
      feels: {
        Irritating: 28.8,
        Luxurious: 27.8,
        Natural: 45.4,
        Nostalgic: 27.8,
        Offensive: 18.0,
        "Old-Fashioned": 55.6,
        Playful: 17.6,
        Refreshing: 40,
        Relaxing: 39.0,
        Romantic: 15.6,
        Soothing: 39.5,
        Sporty: 22.0,
        Surprising: 31.7,
        Trendy: 22.0,
        Vibrant: 26.8,
        Fresh: 46.8,
        Clean: 54.6,
        Artificial: 49.3,
        Cheery: 22.0,
        Comforting: 35.1,
        "like it gives you Confidence": 22.9,
        Dull: 27.8,
        Energising: 37.6,
        Familiar: 43.4,
        Harsh: 35.1,
        Intriguing: 36.6,
      },
      images: {
        "Emotions-I-feel-calm-and-at-peace": 45,
        "Emotions-I-feel-protected-and-reassured": 30,
        "Emotions-This-gives-me-a-burst-of-energy": 42,
        "Emotions-This-gives-me-confidence": 42,
        "Fragrance-Space-I-love-the-light,-airy-scent": 24,
        "Fragrance-Space-I-love-the-warm-essence": 54,
        "Fragrance-Space-It-feels-so-fresh": 48,
        "Fragrance-Space-It-has-a-luxurious-aura-about-it": 12,
        "Occasion-It-puts-me-in-a-meditative-state": 42,
        "Occasion-It's-fun-for-an-intimate-group-outing": 30,
        "Occasion-It's-perfect-for-big-gatherings": 15,
        "Occasion-It's-wonderful-for-spending-time-with-friends": 30,
        "Product-Format-It-does-a-great-job-of-eliminating-odours": 27,
        "Product-Format-It-has-a-brightening-effect": 21,
        "Product-Format-It-lathers-up-very-nicely": 45,
        "Product-Format-This-leaves-me-feeling-soft-and-smooth": 48,
        "Routine-It-helps-me-feel-ready-for-a-great-night-out": 24,
        "Routine-It-helps-me-start-my-day-off-right": 33,
        "Routine-It-helps-me-take-a-moment-just-for-myself": 51,
        "Routine-It-helps-me-wind-down-at-the-end-of-the-day": 51,
        "Sensorial-I-like-the-clean-allusion": 24,
        "Sensorial-I-love-how-smooth-and-creamy-it-is": 36,
        "Sensorial-I-love-the-bright,-sparkling-effect": 36,
        "Sensorial-I-love-the-rich,-deep-feeling": 27,
      },
    },
    {
      id: "HT61",
      citrus: 50,
      gourmand: 50,
      marine: 0,
      woody: 0,
      liking: 74.4,
      feels: {
        Irritating: 15.9,
        Luxurious: 38.6,
        Natural: 65.2,
        Nostalgic: 30.9,
        Offensive: 9.2,
        "Old-Fashioned": 27.1,
        Playful: 44.0,
        Refreshing: 69.1,
        Relaxing: 55.6,
        Romantic: 26.6,
        Soothing: 54.6,
        Sporty: 41.1,
        Surprising: 45.4,
        Trendy: 38.6,
        Vibrant: 58.0,
        Fresh: 73.9,
        Clean: 79.2,
        Artificial: 31.9,
        Cheery: 51.2,
        Comforting: 53.6,
        "like it gives you Confidence": 45.9,
        Dull: 10.1,
        Energising: 57.5,
        Familiar: 51.7,
        Harsh: 21.7,
        Intriguing: 44.4,
      },
      images: {
        "Emotions-I-feel-calm-and-at-peace": 57,
        "Emotions-I-feel-protected-and-reassured": 15,
        "Emotions-This-gives-me-a-burst-of-energy": 42,
        "Emotions-This-gives-me-confidence": 42,
        "Fragrance-Space-I-love-the-light,-airy-scent": 51,
        "Fragrance-Space-I-love-the-warm-essence": 54,
        "Fragrance-Space-It-feels-so-fresh": 57,
        "Fragrance-Space-It-has-a-luxurious-aura-about-it": 24,
        "Occasion-It-puts-me-in-a-meditative-state": 48,
        "Occasion-It's-fun-for-an-intimate-group-outing": 30,
        "Occasion-It's-perfect-for-big-gatherings": 21,
        "Occasion-It's-wonderful-for-spending-time-with-friends": 30,
        "Product-Format-It-does-a-great-job-of-eliminating-odours": 45,
        "Product-Format-It-has-a-brightening-effect": 42,
        "Product-Format-It-lathers-up-very-nicely": 48,
        "Product-Format-This-leaves-me-feeling-soft-and-smooth": 51,
        "Routine-It-helps-me-feel-ready-for-a-great-night-out": 24,
        "Routine-It-helps-me-start-my-day-off-right": 51,
        "Routine-It-helps-me-take-a-moment-just-for-myself": 54,
        "Routine-It-helps-me-wind-down-at-the-end-of-the-day": 54,
        "Sensorial-I-like-the-clean-allusion": 39,
        "Sensorial-I-love-how-smooth-and-creamy-it-is": 57,
        "Sensorial-I-love-the-bright,-sparkling-effect": 51,
        "Sensorial-I-love-the-rich,-deep-feeling": 39,
      },
    },
    {
      id: "JV48",
      citrus: 0,
      gourmand: 0,
      marine: 50,
      woody: 50,
      liking: 38.9,
      feels: {
        Irritating: 37.0,
        Luxurious: 23.6,
        Natural: 46.6,
        Nostalgic: 23.6,
        Offensive: 27.4,
        "Old-Fashioned": 53.4,
        Playful: 16.8,
        Refreshing: 38.0,
        Relaxing: 34.1,
        Romantic: 12.0,
        Soothing: 29.3,
        Sporty: 28.8,
        Surprising: 31.2,
        Trendy: 17.8,
        Vibrant: 26.9,
        Fresh: 41.8,
        Clean: 46.6,
        Artificial: 49.5,
        Cheery: 18.3,
        Comforting: 31.2,
        "like it gives you Confidence": 23.6,
        Dull: 34.6,
        Energising: 30.3,
        Familiar: 36.1,
        Harsh: 41.8,
        Intriguing: 35.6,
      },
      images: {
        "Emotions-I-feel-calm-and-at-peace": 54,
        "Emotions-I-feel-protected-and-reassured": 18,
        "Emotions-This-gives-me-a-burst-of-energy": 42,
        "Emotions-This-gives-me-confidence": 42,
        "Fragrance-Space-I-love-the-light,-airy-scent": 36,
        "Fragrance-Space-I-love-the-warm-essence": 39,
        "Fragrance-Space-It-feels-so-fresh": 33,
        "Fragrance-Space-It-has-a-luxurious-aura-about-it": 18,
        "Occasion-It-puts-me-in-a-meditative-state": 36,
        "Occasion-It's-fun-for-an-intimate-group-outing": 27,
        "Occasion-It's-perfect-for-big-gatherings": 21,
        "Occasion-It's-wonderful-for-spending-time-with-friends": 6,
        "Product-Format-It-does-a-great-job-of-eliminating-odours": 42,
        "Product-Format-It-has-a-brightening-effect": 15,
        "Product-Format-It-lathers-up-very-nicely": 45,
        "Product-Format-This-leaves-me-feeling-soft-and-smooth": 27,
        "Routine-It-helps-me-feel-ready-for-a-great-night-out": 21,
        "Routine-It-helps-me-start-my-day-off-right": 33,
        "Routine-It-helps-me-take-a-moment-just-for-myself": 42,
        "Routine-It-helps-me-wind-down-at-the-end-of-the-day": 33,
        "Sensorial-I-like-the-clean-allusion": 15,
        "Sensorial-I-love-how-smooth-and-creamy-it-is": 30,
        "Sensorial-I-love-the-bright,-sparkling-effect": 36,
        "Sensorial-I-love-the-rich,-deep-feeling": 27,
      },
    },
    {
      id: "KF92",
      citrus: 0,
      gourmand: 100,
      marine: 0,
      woody: 0,
      liking: 69.6,
      feels: {
        Irritating: 13.7,
        Luxurious: 45.1,
        Natural: 63.7,
        Nostalgic: 42.2,
        Offensive: 11.8,
        "Old-Fashioned": 35.8,
        Playful: 32.4,
        Refreshing: 41.7,
        Relaxing: 69.1,
        Romantic: 37.3,
        Soothing: 67.2,
        Sporty: 14.2,
        Surprising: 36.3,
        Trendy: 33.8,
        Vibrant: 26.0,
        Fresh: 54.4,
        Clean: 64.7,
        Artificial: 30.9,
        Cheery: 35.3,
        Comforting: 66.7,
        "like it gives you Confidence": 38.2,
        Dull: 24.0,
        Energising: 27.0,
        Familiar: 55.4,
        Harsh: 10.8,
        Intriguing: 48.5,
      },
      images: {
        "Emotions-I-feel-calm-and-at-peace": 51,
        "Emotions-I-feel-protected-and-reassured": 48,
        "Emotions-This-gives-me-a-burst-of-energy": 18,
        "Emotions-This-gives-me-confidence": 24,
        "Fragrance-Space-I-love-the-light,-airy-scent": 45,
        "Fragrance-Space-I-love-the-warm-essence": 54,
        "Fragrance-Space-It-feels-so-fresh": 24,
        "Fragrance-Space-It-has-a-luxurious-aura-about-it": 12,
        "Occasion-It-puts-me-in-a-meditative-state": 33,
        "Occasion-It's-fun-for-an-intimate-group-outing": 18,
        "Occasion-It's-perfect-for-big-gatherings": 18,
        "Occasion-It's-wonderful-for-spending-time-with-friends": 24,
        "Product-Format-It-does-a-great-job-of-eliminating-odours": 48,
        "Product-Format-It-has-a-brightening-effect": 39,
        "Product-Format-It-lathers-up-very-nicely": 72,
        "Product-Format-This-leaves-me-feeling-soft-and-smooth": 48,
        "Routine-It-helps-me-feel-ready-for-a-great-night-out": 24,
        "Routine-It-helps-me-start-my-day-off-right": 60,
        "Routine-It-helps-me-take-a-moment-just-for-myself": 75,
        "Routine-It-helps-me-wind-down-at-the-end-of-the-day": 57,
        "Sensorial-I-like-the-clean-allusion": 42,
        "Sensorial-I-love-how-smooth-and-creamy-it-is": 72,
        "Sensorial-I-love-the-bright,-sparkling-effect": 39,
        "Sensorial-I-love-the-rich,-deep-feeling": 42,
      },
    },
    {
      id: "LM04",
      citrus: 0,
      gourmand: 0,
      marine: 0,
      woody: 100,
      liking: 30.7,
      feels: {
        Irritating: 41.5,
        Luxurious: 19.0,
        Natural: 46.3,
        Nostalgic: 27.8,
        Offensive: 29.3,
        "Old-Fashioned": 62.0,
        Playful: 14.6,
        Refreshing: 27.3,
        Relaxing: 24.4,
        Romantic: 9.3,
        Soothing: 28.8,
        Sporty: 24.4,
        Surprising: 31.2,
        Trendy: 17.1,
        Vibrant: 23.9,
        Fresh: 37.1,
        Clean: 39.0,
        Artificial: 52.7,
        Cheery: 13.7,
        Comforting: 22.4,
        "like it gives you Confidence": 19.5,
        Dull: 42.0,
        Energising: 24.4,
        Familiar: 34.6,
        Harsh: 47.3,
        Intriguing: 30.7,
      },
      images: {
        "Emotions-I-feel-calm-and-at-peace": 33,
        "Emotions-I-feel-protected-and-reassured": 24,
        "Emotions-This-gives-me-a-burst-of-energy": 45,
        "Emotions-This-gives-me-confidence": 51,
        "Fragrance-Space-I-love-the-light,-airy-scent": 15,
        "Fragrance-Space-I-love-the-warm-essence": 30,
        "Fragrance-Space-It-feels-so-fresh": 42,
        "Fragrance-Space-It-has-a-luxurious-aura-about-it": 18,
        "Occasion-It-puts-me-in-a-meditative-state": 54,
        "Occasion-It's-fun-for-an-intimate-group-outing": 24,
        "Occasion-It's-perfect-for-big-gatherings": 33,
        "Occasion-It's-wonderful-for-spending-time-with-friends": 27,
        "Product-Format-It-does-a-great-job-of-eliminating-odours": 24,
        "Product-Format-It-has-a-brightening-effect": 18,
        "Product-Format-It-lathers-up-very-nicely": 30,
        "Product-Format-This-leaves-me-feeling-soft-and-smooth": 27,
        "Routine-It-helps-me-feel-ready-for-a-great-night-out": 36,
        "Routine-It-helps-me-start-my-day-off-right": 15,
        "Routine-It-helps-me-take-a-moment-just-for-myself": 39,
        "Routine-It-helps-me-wind-down-at-the-end-of-the-day": 30,
        "Sensorial-I-like-the-clean-allusion": 27,
        "Sensorial-I-love-how-smooth-and-creamy-it-is": 21,
        "Sensorial-I-love-the-bright,-sparkling-effect": 27,
        "Sensorial-I-love-the-rich,-deep-feeling": 27,
      },
    },
    {
      id: "MW90",
      citrus: 0,
      gourmand: 50,
      marine: 0,
      woody: 50,
      liking: 42.6,
      feels: {
        Irritating: 32.4,
        Luxurious: 26.0,
        Natural: 44.1,
        Nostalgic: 30.4,
        Offensive: 26.0,
        "Old-Fashioned": 56.4,
        Playful: 17.2,
        Refreshing: 35.3,
        Relaxing: 40.2,
        Romantic: 19.1,
        Soothing: 38.7,
        Sporty: 21.6,
        Surprising: 31.4,
        Trendy: 22.5,
        Vibrant: 29.4,
        Fresh: 41.7,
        Clean: 50,
        Artificial: 45.1,
        Cheery: 20.6,
        Comforting: 36.3,
        "like it gives you Confidence": 28.4,
        Dull: 30.9,
        Energising: 30.4,
        Familiar: 36.8,
        Harsh: 38.7,
        Intriguing: 37.7,
      },
      images: {
        "Emotions-I-feel-calm-and-at-peace": 33,
        "Emotions-I-feel-protected-and-reassured": 21,
        "Emotions-This-gives-me-a-burst-of-energy": 36,
        "Emotions-This-gives-me-confidence": 42,
        "Fragrance-Space-I-love-the-light,-airy-scent": 30,
        "Fragrance-Space-I-love-the-warm-essence": 60,
        "Fragrance-Space-It-feels-so-fresh": 39,
        "Fragrance-Space-It-has-a-luxurious-aura-about-it": 27,
        "Occasion-It-puts-me-in-a-meditative-state": 27,
        "Occasion-It's-fun-for-an-intimate-group-outing": 21,
        "Occasion-It's-perfect-for-big-gatherings": 18,
        "Occasion-It's-wonderful-for-spending-time-with-friends": 18,
        "Product-Format-It-does-a-great-job-of-eliminating-odours": 24,
        "Product-Format-It-has-a-brightening-effect": 24,
        "Product-Format-It-lathers-up-very-nicely": 33,
        "Product-Format-This-leaves-me-feeling-soft-and-smooth": 33,
        "Routine-It-helps-me-feel-ready-for-a-great-night-out": 36,
        "Routine-It-helps-me-start-my-day-off-right": 33,
        "Routine-It-helps-me-take-a-moment-just-for-myself": 51,
        "Routine-It-helps-me-wind-down-at-the-end-of-the-day": 33,
        "Sensorial-I-like-the-clean-allusion": 30,
        "Sensorial-I-love-how-smooth-and-creamy-it-is": 27,
        "Sensorial-I-love-the-bright,-sparkling-effect": 33,
        "Sensorial-I-love-the-rich,-deep-feeling": 51,
      },
    },
    {
      id: "NX73",
      citrus: 50,
      gourmand: 0,
      marine: 0,
      woody: 50,
      liking: 54.9,
      feels: {
        Irritating: 23.5,
        Luxurious: 24.0,
        Natural: 47.1,
        Nostalgic: 25,
        Offensive: 17.6,
        "Old-Fashioned": 36.8,
        Playful: 31.4,
        Refreshing: 56.9,
        Relaxing: 36.8,
        Romantic: 16.7,
        Soothing: 37.7,
        Sporty: 33.8,
        Surprising: 37.7,
        Trendy: 26.5,
        Vibrant: 50,
        Fresh: 62.3,
        Clean: 63.2,
        Artificial: 44.6,
        Cheery: 33.8,
        Comforting: 36.8,
        "like it gives you Confidence": 34.8,
        Dull: 17.2,
        Energising: 49.5,
        Familiar: 43.6,
        Harsh: 34.3,
        Intriguing: 40.2,
      },
      images: {
        "Emotions-I-feel-calm-and-at-peace": 30,
        "Emotions-I-feel-protected-and-reassured": 9,
        "Emotions-This-gives-me-a-burst-of-energy": 33,
        "Emotions-This-gives-me-confidence": 42,
        "Fragrance-Space-I-love-the-light,-airy-scent": 36,
        "Fragrance-Space-I-love-the-warm-essence": 30,
        "Fragrance-Space-It-feels-so-fresh": 54,
        "Fragrance-Space-It-has-a-luxurious-aura-about-it": 9,
        "Occasion-It-puts-me-in-a-meditative-state": 39,
        "Occasion-It's-fun-for-an-intimate-group-outing": 36,
        "Occasion-It's-perfect-for-big-gatherings": 39,
        "Occasion-It's-wonderful-for-spending-time-with-friends": 30,
        "Product-Format-It-does-a-great-job-of-eliminating-odours": 39,
        "Product-Format-It-has-a-brightening-effect": 24,
        "Product-Format-It-lathers-up-very-nicely": 57,
        "Product-Format-This-leaves-me-feeling-soft-and-smooth": 51,
        "Routine-It-helps-me-feel-ready-for-a-great-night-out": 30,
        "Routine-It-helps-me-start-my-day-off-right": 33,
        "Routine-It-helps-me-take-a-moment-just-for-myself": 54,
        "Routine-It-helps-me-wind-down-at-the-end-of-the-day": 36,
        "Sensorial-I-like-the-clean-allusion": 36,
        "Sensorial-I-love-how-smooth-and-creamy-it-is": 39,
        "Sensorial-I-love-the-bright,-sparkling-effect": 51,
        "Sensorial-I-love-the-rich,-deep-feeling": 30,
      },
    },
    {
      id: "PE26",
      citrus: 0,
      gourmand: 50,
      marine: 50,
      woody: 0,
      liking: 60.7,
      feels: {
        Irritating: 17.0,
        Luxurious: 40.3,
        Natural: 55.8,
        Nostalgic: 35.0,
        Offensive: 11.7,
        "Old-Fashioned": 41.7,
        Playful: 27.2,
        Refreshing: 43.2,
        Relaxing: 57.3,
        Romantic: 32.0,
        Soothing: 53.9,
        Sporty: 18.0,
        Surprising: 32.0,
        Trendy: 32.5,
        Vibrant: 28.6,
        Fresh: 50.5,
        Clean: 60.2,
        Artificial: 37.4,
        Cheery: 29.6,
        Comforting: 51.5,
        "like it gives you Confidence": 33.5,
        Dull: 29.1,
        Energising: 28.2,
        Familiar: 45.1,
        Harsh: 14.6,
        Intriguing: 41.3,
      },
      images: {
        "Emotions-I-feel-calm-and-at-peace": 36,
        "Emotions-I-feel-protected-and-reassured": 33,
        "Emotions-This-gives-me-a-burst-of-energy": 27,
        "Emotions-This-gives-me-confidence": 15,
        "Fragrance-Space-I-love-the-light,-airy-scent": 42,
        "Fragrance-Space-I-love-the-warm-essence": 54,
        "Fragrance-Space-It-feels-so-fresh": 27,
        "Fragrance-Space-It-has-a-luxurious-aura-about-it": 12,
        "Occasion-It-puts-me-in-a-meditative-state": 54,
        "Occasion-It's-fun-for-an-intimate-group-outing": 36,
        "Occasion-It's-perfect-for-big-gatherings": 21,
        "Occasion-It's-wonderful-for-spending-time-with-friends": 30,
        "Product-Format-It-does-a-great-job-of-eliminating-odours": 48,
        "Product-Format-It-has-a-brightening-effect": 42,
        "Product-Format-It-lathers-up-very-nicely": 63,
        "Product-Format-This-leaves-me-feeling-soft-and-smooth": 45,
        "Routine-It-helps-me-feel-ready-for-a-great-night-out": 30,
        "Routine-It-helps-me-start-my-day-off-right": 54,
        "Routine-It-helps-me-take-a-moment-just-for-myself": 60,
        "Routine-It-helps-me-wind-down-at-the-end-of-the-day": 51,
        "Sensorial-I-like-the-clean-allusion": 27,
        "Sensorial-I-love-how-smooth-and-creamy-it-is": 72,
        "Sensorial-I-love-the-bright,-sparkling-effect": 39,
        "Sensorial-I-love-the-rich,-deep-feeling": 39,
      },
    },
    {
      id: "RD58",
      citrus: 0,
      gourmand: 0,
      marine: 100,
      woody: 0,
      liking: 43.3,
      feels: {
        Irritating: 28.4,
        Luxurious: 21.6,
        Natural: 47.6,
        Nostalgic: 25.5,
        Offensive: 19.2,
        "Old-Fashioned": 38.9,
        Playful: 21.6,
        Refreshing: 39.9,
        Relaxing: 38.9,
        Romantic: 17.8,
        Soothing: 34.1,
        Sporty: 19.7,
        Surprising: 27.4,
        Trendy: 19.2,
        Vibrant: 27.9,
        Fresh: 46.2,
        Clean: 54.8,
        Artificial: 44.2,
        Cheery: 24.5,
        Comforting: 39.4,
        "like it gives you Confidence": 23.6,
        Dull: 39.9,
        Energising: 27.9,
        Familiar: 36.5,
        Harsh: 24.0,
        Intriguing: 30.8,
      },
      images: {
        "Emotions-I-feel-calm-and-at-peace": 48,
        "Emotions-I-feel-protected-and-reassured": 24,
        "Emotions-This-gives-me-a-burst-of-energy": 33,
        "Emotions-This-gives-me-confidence": 33,
        "Fragrance-Space-I-love-the-light,-airy-scent": 39,
        "Fragrance-Space-I-love-the-warm-essence": 33,
        "Fragrance-Space-It-feels-so-fresh": 39,
        "Fragrance-Space-It-has-a-luxurious-aura-about-it": 6,
        "Occasion-It-puts-me-in-a-meditative-state": 39,
        "Occasion-It's-fun-for-an-intimate-group-outing": 33,
        "Occasion-It's-perfect-for-big-gatherings": 3,
        "Occasion-It's-wonderful-for-spending-time-with-friends": 24,
        "Product-Format-It-does-a-great-job-of-eliminating-odours": 45,
        "Product-Format-It-has-a-brightening-effect": 24,
        "Product-Format-It-lathers-up-very-nicely": 45,
        "Product-Format-This-leaves-me-feeling-soft-and-smooth": 33,
        "Routine-It-helps-me-feel-ready-for-a-great-night-out": 24,
        "Routine-It-helps-me-start-my-day-off-right": 39,
        "Routine-It-helps-me-take-a-moment-just-for-myself": 39,
        "Routine-It-helps-me-wind-down-at-the-end-of-the-day": 48,
        "Sensorial-I-like-the-clean-allusion": 30,
        "Sensorial-I-love-how-smooth-and-creamy-it-is": 45,
        "Sensorial-I-love-the-bright,-sparkling-effect": 33,
        "Sensorial-I-love-the-rich,-deep-feeling": 33,
      },
    },
    {
      id: "UK32",
      citrus: 33.33,
      gourmand: 0,
      marine: 33.34,
      woody: 33.33,
      liking: 55.5,
      feels: {
        Irritating: 23.4,
        Luxurious: 27.8,
        Natural: 57.4,
        Nostalgic: 26.3,
        Offensive: 20.6,
        "Old-Fashioned": 38.8,
        Playful: 34.0,
        Refreshing: 61.7,
        Relaxing: 42.1,
        Romantic: 17.7,
        Soothing: 42.6,
        Sporty: 36.4,
        Surprising: 44.5,
        Trendy: 30.6,
        Vibrant: 47.8,
        Fresh: 68.4,
        Clean: 67.5,
        Artificial: 39.7,
        Cheery: 36.4,
        Comforting: 38.3,
        "like it gives you Confidence": 36.8,
        Dull: 17.2,
        Energising: 52.6,
        Familiar: 44.5,
        Harsh: 33.0,
        Intriguing: 37.3,
      },
      images: {
        "Emotions-I-feel-calm-and-at-peace": 51,
        "Emotions-I-feel-protected-and-reassured": 9,
        "Emotions-This-gives-me-a-burst-of-energy": 57,
        "Emotions-This-gives-me-confidence": 54,
        "Fragrance-Space-I-love-the-light,-airy-scent": 54,
        "Fragrance-Space-I-love-the-warm-essence": 39,
        "Fragrance-Space-It-feels-so-fresh": 42,
        "Fragrance-Space-It-has-a-luxurious-aura-about-it": 27,
        "Occasion-It-puts-me-in-a-meditative-state": 33,
        "Occasion-It's-fun-for-an-intimate-group-outing": 36,
        "Occasion-It's-perfect-for-big-gatherings": 24,
        "Occasion-It's-wonderful-for-spending-time-with-friends": 27,
        "Product-Format-It-does-a-great-job-of-eliminating-odours": 30,
        "Product-Format-It-has-a-brightening-effect": 33,
        "Product-Format-It-lathers-up-very-nicely": 42,
        "Product-Format-This-leaves-me-feeling-soft-and-smooth": 45,
        "Routine-It-helps-me-feel-ready-for-a-great-night-out": 27,
        "Routine-It-helps-me-start-my-day-off-right": 48,
        "Routine-It-helps-me-take-a-moment-just-for-myself": 45,
        "Routine-It-helps-me-wind-down-at-the-end-of-the-day": 30,
        "Sensorial-I-like-the-clean-allusion": 30,
        "Sensorial-I-love-how-smooth-and-creamy-it-is": 33,
        "Sensorial-I-love-the-bright,-sparkling-effect": 36,
        "Sensorial-I-love-the-rich,-deep-feeling": 36,
      },
    },
  ],
  feels: [
    "Irritating",
    "Luxurious",
    "Natural",
    "Nostalgic",
    "Offensive",
    "Old-Fashioned",
    "Playful",
    "Refreshing",
    "Relaxing",
    "Romantic",
    "Soothing",
    "Sporty",
    "Surprising",
    "Trendy",
    "Vibrant",
    "Fresh",
    "Clean",
    "Artificial",
    "Cheery",
    "Comforting",
    "like it gives you Confidence",
    "Dull",
    "Energising",
    "Familiar",
    "Harsh",
    "Intriguing",
  ],
  images: [
    "Emotions-I-feel-calm-and-at-peace",
    "Emotions-I-feel-protected-and-reassured",
    "Emotions-This-gives-me-a-burst-of-energy",
    "Emotions-This-gives-me-confidence",
    "Fragrance-Space-I-love-the-light,-airy-scent",
    "Fragrance-Space-I-love-the-warm-essence",
    "Fragrance-Space-It-feels-so-fresh",
    "Fragrance-Space-It-has-a-luxurious-aura-about-it",
    "Occasion-It-puts-me-in-a-meditative-state",
    "Occasion-It's-fun-for-an-intimate-group-outing",
    "Occasion-It's-perfect-for-big-gatherings",
    "Occasion-It's-wonderful-for-spending-time-with-friends",
    "Product-Format-It-does-a-great-job-of-eliminating-odours",
    "Product-Format-It-has-a-brightening-effect",
    "Product-Format-It-lathers-up-very-nicely",
    "Product-Format-This-leaves-me-feeling-soft-and-smooth",
    "Routine-It-helps-me-feel-ready-for-a-great-night-out",
    "Routine-It-helps-me-start-my-day-off-right",
    "Routine-It-helps-me-take-a-moment-just-for-myself",
    "Routine-It-helps-me-wind-down-at-the-end-of-the-day",
    "Sensorial-I-like-the-clean-allusion",
    "Sensorial-I-love-how-smooth-and-creamy-it-is",
    "Sensorial-I-love-the-bright,-sparkling-effect",
    "Sensorial-I-love-the-rich,-deep-feeling",
  ],
} as const;

export default DATA;
